#!/usr/bin/env python3

import datetime
import json
import random

from twilio.rest import Client

CONFIG_FILE = "/etc/friday-notifier.conf"

def send_msg(config, body):
    for target in config["targets"]:
        print("Messaging " + target)
        client = Client(config["api_key"], config["api_secret"], config["account_sid"])
        client.api.account.messages.create(to=target,
                                           from_=config["from"],
                                           body=body)


def generate_message():
    it_is_friday = [
        'It\'s Friday!!!!!!!',
        'It appears to be Friday!',
        'Unless I\'m very much mistaken, it is Friday.',
        'This is your weekly alert of the occurence of Friday!',
        'Friday has occured! (Like it did this time last week.)',
        'I would like to inform you it is Friday today!',
    ]

    greeting = [
        'I hope you enjoy your day!',
        'Make the most of it - it won\'t happen again for another week!',
        'Enjoy it while it lasts!',
        'Have a great day!',
        'Use this day wisely!',
        'Enjoy this weekly occurence!',
        'Have a great day!',
    ]

    special_greeting = [
        'Do not take your work home with you.',
        'Make sure to enjoy your day! (That is mandatory)',
        'Please partake in mandatory enjoyment of this day.',
        'Enjoy this day as much as you can!',
    ]

    random_notification = random.choice(it_is_friday)
    random_greeting = random.choice(greeting)

    # one-time special message override
    now = datetime.datetime.today()
    if now.day == 30 and now.month == 10 and now.year == 2020:
        random_notification = "Merry Fri-Birth-Retirement-Day!"
        random_greeting = random.choice(special_greeting)


    return "%s %s" % (random_notification, random_greeting)

def main():
    random.seed()
    with open(CONFIG_FILE, "r") as config_handle:
        config = json.load(config_handle)

    day = datetime.datetime.today().weekday()
    if day == 4:
        send_msg(config, generate_message())
    if not config['debug']:
        print("Not Friday. Exiting.")
        exit(0)
    if day > 4:
        send_msg(config, "It isn't Friday, though it's still the weekend!")
    elif day < 4:
        send_msg(config, "Unfortunately, it isn't Friday. I'm so sorry...")

if __name__ == "__main__":
    main()
